# Dot Product, Norms, and Distance

In [1]:
import numpy as np

In [2]:
x = np.array([-2,1,0,-1])
y = np.array([2,3,-6,0])
z = np.array([2,-6,9,0])

In [3]:
SUM = x + y
print(SUM)

[ 0  4 -6 -1]


In [4]:
LC = 2*x + 7*y
print(LC)

[ 10  23 -42  -2]


## Dot Product

In [7]:
dot = x @ y
print(dot)

-1


In [9]:
dot_ulit = np.dot(x,y)
print(dot_ulit)

-1


## Norm

In [10]:
norm = np.linalg.norm(x)
print(norm)

2.449489742783178


Calculate $(\vec x \cdot \vec y)\vec y + \|\vec x\|^2\, \vec z$.

In [13]:
sara = (dot*y)+((norm**2)*z)
print(sara)

[ 10. -39.  60.   0.]


(2)    $\|\|\vec x - \vec y\|\vec z\|$

In [15]:
curlee = np.linalg.norm(np.linalg.norm(x - y) * z)
print(curlee)

83.04817878797826


(3) $(\vec x\cdot\vec z)\vec y + (\vec y\cdot \vec z)$

In [19]:
2 + np.array([1,2,3])

array([3, 4, 5])

In [20]:
jinggoy = ((x @ z) * y) + (y @ z)
print(jinggoy)

[-88 -98  -8 -68]


In linear algebra, however, the expression is **not** defined.

**EXERCISE** Write a program that calculates the sum of components of the vector 

$\vec x= \begin{bmatrix}
1 \\ 2\\ 3\\ 4
\end{bmatrix}$

In [21]:
vec_x = np.array([1,2,3,4])

In [23]:
sum_entries = vec_x[0] + vec_x[1] + vec_x[2] + vec_x[3]
print(sum_entries)

10


In [26]:
ones = np.ones(4)

In [27]:
sum_entries_ulit = vec_x @ ones
print(sum_entries_ulit)

10.0


# Matrices

$A=\begin{bmatrix}
-3 & 0 & 2\\
1 & 2 & -2
\end{bmatrix}$ and $B=\begin{bmatrix}
1 & 3 & -4\\
-3 & -2 & 0
\end{bmatrix}$

In [28]:
A = np.array([[-3,0,2],[1,2,-2]])
B = np.array([[1,3,-4],[-3,-2,0]])

In [29]:
print(A.shape)

(2, 3)


In [30]:
print(B.shape)

(2, 3)


In [31]:
C = A+B
print(C)

[[-2  3 -2]
 [-2  0 -2]]


In [33]:
E = 2*A + (-3)*B
print(E)

[[-9 -9 16]
 [11 10 -4]]


In [34]:
F = np.array([[1,2],[3,4],[5,6]])
print(F.shape)

(3, 2)


In [35]:
print(A+F)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [36]:
X = np.array([[2,1],[-3,4],[1,6]])
Y = np.array([[0,-1,0],[4,0,2],[8,-1,7]])

In [37]:
print(X @ Y)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [38]:
print(Y @ X)

[[ 3 -4]
 [10 16]
 [26 46]]


In [39]:
print(np.matmul(Y,X))

[[ 3 -4]
 [10 16]
 [26 46]]


In [40]:
print(np.dot(Y,X))

[[ 3 -4]
 [10 16]
 [26 46]]
